version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mityahar_postgres
    restart: always
    environment:
      POSTGRES_DB: mityahar_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mityahar_dev
    ports:
      - "5432:5432"
    volumes:
      - mityahar_pg_data:/var/lib/postgresql/data

volumes:
  mityahar_pg_data:
